apiVersion: v1
kind: Service
metadata:
  name: svc-toggens-perf-test
  labels:
    toggens-perf-test
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    - port: {{ .Values.service.jmx }}
      targetPort: jmx
      protocol: TCP
      name: jmx
  selector:
    app: toggens-perf-test
